model_type: unet
padding_mode: "zeros"
n_input_scalar_components: 1
n_input_vector_components: 0
n_output_scalar_components: 1
n_output_vector_components: 0
time_history: 1
time_future: 1
hidden_channels: 32
activation: relu
norm: true
ch_mults:
  - 1
  - 2
  - 2
  - 4
is_attn:
  - true
  - true
  - true
  - true
mid_attn: true
param_conditioning: "scalar"
