model_type: unet
padding_mode: "zeros"
n_input_scalar_components: 1
n_input_vector_components: 0
n_output_scalar_components: 1
n_output_vector_components: 0
time_history: 5
time_future: 10
hidden_channels: 64
activation: relu
norm: True
ch_mults:
  - 1
  - 2
  - 2
  - 4
is_attn:
  - True
  - True
  - True
  - True
mid_attn: True
param_conditioning: "scalar"
