name: external

type: statebystate
time_gap: false

train_val:
  split: true
  external: true
  input_val:
    path: output_surrogate/train_split/random_starts.txt
    repo_relative: true
  input_train:
    path: output_surrogate/train_split/global_ids_train_new_10step.txt
    repo_relative: true

global_ids:
  save: true
  output:
    path: output_surrogate/third_unet
    repo_relative: true
    exists_ok: true

normalization: perpair
