name: future_gap

type: statebystate
time_gap: True

train_val:
  external: False
  split: True
  ratio: 0.01
  seed: 42

global_ids:
  save: True
  output:
    path: "output_surrogate/unet_attention_first"
    repo_relative: True
    exists_ok: False

normalization: perpair
