name: future_gap

type: statebystate
time_gap: true

train_val:
  split: true
  external: true
  input_val:
    path: output_surrogate/train_split/global_ids_val_gap.txt
    repo_relative: true
  input_train:
    path: output_surrogate/train_split/global_ids_val_gap.txt
    repo_relative: true
global_ids:
  save: true
  output:
    path: "output_surrogate/four_unet_gap"
    repo_relative: true
    exists_ok: false

normalization: perpair
