name: external

type: statebystate

train_val:
  external: False
  split: True
  ratio: 0.2
  seed: 42

global_ids:
  save: True
  output:
    path: "output_surrogate/train_split"
    repo_relative: True
    exists_ok: False

normalization: minmax
